language: node_js
node_js:
  - '0.10'
before_install:
  - mkdir -p "$HOME"/.local/lib/python2.7/site-packages
  - export PYTHONPATH="$HOME"/.local/lib/python2.7/site-packages:"$PYTHONPATH"
  - "npm install && ./bin/travisaction $CI_ACTION before_install"
script: "./bin/travisaction $CI_ACTION script"
env:
  - CI_ACTION="mocha"
  - CI_ACTION="gjslint"
